## Gliederung der Arbeit {#sec-gliederung}

Die Grundlagen der Finite Elemente Methode sind in [Kapitel @sec-Grundlagen-FEM] dargestellt. Dabei werden zunächst diverse Elementansätze für finite Elemente erläutert und deren Kontinuität dargestellt. Weiterhin werden die mathematischen Werkzeuge zur Anwendung der FEM beschrieben und in @sec-einfuehrungsbeispiel auf das Einführungsbeispiel angewandt.

Die zur Analyse notwendigen Differentialgleichungen einer Platte nach Kirchhoff werden in @sec-mech-math-grundlagen hergeleitet.  Weiterhin sind die mathematisch relevanten Grundlagen für die aus der DGL entstehenden Funktionale sowie die Cialet’sche Definition eines finiten Elements in @sec-mech-math-grundlagen aufgeführt.

Für die Analyse von Plattentragwerken wird dann in @sec-fem-plattentragwerke zunächst die allgemeines schwache Form des Problems hergeleitet um danach die globale Steifigkeitsmatrix sowohl für das Rechteckelement nach Bogner Fox und Schmitt als auch für das allgemeine DKQ Element zu berechnen.

Die programmtechnische Umsetzung in der noch sehr neuen Programmierumgebung JULIA, sowie die Anwendung auf Beispiele zur Testung, sind in @sec-Umsetzung-Julia-Beispiele dokumentiert.