## Problemstellung {#sec-problemstellung}

Die Analyse von Plattentragwerken ist eine zentrale Aufgabe im Bauingenieurwesen, da sie in einer Vielzahl von Konstruktionen eine wesentliche Rolle spielen. Die Ingenieursliteratur zur Implementierung der FEM für Kirchhoff-Platten beschränkt sich oft auf rechteckige Elemente und ist auch hier teilweise lückenhaft. Für die Berechnung komplexer Strukturen ist die Formulierung für allgemeine Vierecke jedoch von wesentlicher Bedeutung.

Die Verträglichkeit der Rotation von benachbarten Elemente stellt bei der Finite Elemente Analyse eine besondere Herausforderung dar. Ist die Verträglichkeit bei benachbarten Rechteckelementen am gemeinsamen Knoten gegeben, sodass bei der Darstellung der Rotationen keine Unstetigkeiten vorhanden sind, so wird bei dem Elementansatz von einer sogenannten $C^1$-Kontinuität gesprochen. Diese Kontinuität erfüllt der kubische Ansatz des Bogner-Fox-Schmitt Elements. Für die Berechnung allgemeiner Vierecke ist dieser Ansatz jedoch unbrauchbar, da der zusätzliche Freiheitsgrad $\theta_{\xi\eta}$ störend wirkt. 

Ziel dieser Arbeit ist die Herleitung einer ausgewählten Formulierung für allgemeine Vierecke, sowie die Implementierung in der Programmierumgebung JULIA. An ausgewählten Anwendungsbeispielen wird die Umsetzung verifiziert und dadurch eine offene und nachvollziehbare Lösung für die Anwendung der Kirchhoff-Plattentheorie geschaffen.

Zudem ist das grundlegende Verständnis der Finite Elemente Methode und etablierter Elementansätze von großer Wichtigkeit. Die Erläuterung numerischer Methoden für die Kirchhoffsche Plattentheorie ist, vor allem in der deutschsprachigen Literatur, bisher sehr lückenhaft. Daher stellt die Aufarbeitung theoretischer Grundlagen, die zur Formulierung der FEM für Kirchhoff-Platten notwendig sind, ein weiteres Ziel dar. Dies beinhaltet sowohl mechanischen Zusammenhänge, als auch mathematische Verfahren.