```{julia}
include("../src/setup.jl")
```


```{julia}
Hx,Hy =HxHy()
printH(Hx,Hy)
```

```{julia}
[ -1 1 1 -1; -1 -1 1 1]
serendipityelement(V)
```

Anna Pag
N1 = -0.25x₁²x₂-0.25x₁x₂²+0.25x₁²+0.25x₁x₂+0.25x₂²-0.25
N2 = -0.25x₁²x₂+0.25x₁x₂²+0.25x₁²-0.25x₁x₂+0.25x₂²-0.25
N3 = 0.25x₁²x₂+0.25x₁x₂²+0.25x₁²+0.25x₁x₂+0.25x₂²-0.25
N4 = 0.25x₁²x₂-0.25x₁x₂²+0.25x₁²-0.25x₁x₂+0.25x₂²-0.25
N5 =  0.5x₁²x₂ - 0.5x₁² - 0.5x₂ + 0.5
N6 = -0.5x₁x₂² - 0.5x₂² + 0.5x₁ + 0.5
N7 = -0.5x₁²x₂ - 0.5x₁² + 0.5x₂ + 0.5
N8 =  0.5x₁x₂² - 0.5x₂² - 0.5x₁ + 0.5

Zienkewicz
N1 = 0.25 (1 - x₁)(1 - x₂)(-x₁ - x₂ - 1)
N2 = 0.25 (1 + x₁)(1 - x₂)( x₁ - x₂ - 1)
N3 = 0.25 (1 + x₁)(1 + x₂)( x₁ + x₂ - 1)
N4 = 0.25 (1 - x₁)(1 + x₂)(-x₁ + x₂ - 1)
N5 = 0.50 (1 - x₁^2)(1 - x₂) = 0.5 - 0.5x₂ + 0.5x₁^2x₂ - 0.5x₁^2 passt
N6 = 0.50 (1 + x₁)(1 - x₂^2) = 0.5 + 0.5x₁ - 0.5x₁x₂^2 - 0.5x₂^2 passt
N7 = 0.50 (1 - x₁^2)(1 + x₂) = 0.5 + 0.5x₂ - 0.5x₁^2x₂ - 0.5x₁^2 passt
N8 = 0.50 (1 - x₁)(1 - x₂^2) = 0.5 - 0.5x₁ + 0.5x₁x₂^2 - 0.5x₂^2 passt


# Überprüfung Hx
Anna Pag
N1      N2      N3      N4      N5                          N6                          N7                          N8
0       0       0       0       (-3S₅)/(2l₁₂)               0                           0                           (3S₈)/(2l₄₁)
0       0       0       0       -0.75C₅*S₅                  0                           0                           -0.75C₈*S₈
1       0       0       0       (1//16)*(8(C₅^2) - 4(S₅^2)) 0                           0                           (1//16)*(8(C₈^2) - 4(S₈^2))
0       0       0       0       (3S₅) / (2l₁₂)              (-3S₆) / (2l₂₃)             0                           0
0       0       0       0       -0.75C₅*S₅                  -0.75C₆*S₆                  0                           0
0       1       0       0       (1//16)*(8(C₅^2) - 4(S₅^2)) (1//16)*(8(C₆^2) - 4(S₆^2)) 0                           0
0       0       0       0       0                           (3S₆) / (2l₂₃)              (-3S₇) / (2l₃₄)             0
0       0       0       0       0                           -0.75C₆*S₆                  -0.75C₇*S₇                  0
0       0       1       0       0                           (1//16)*(8(C₆^2) - 4(S₆^2)) (1//16)*(8(C₇^2) - 4(S₇^2)) 0   
0       0       0       0       0                           0                           (3S₇) / (2l₃₄)              (-3S₈) / (2l₄₁)
0       0       0       0       0                           0                           -0.75C₇*S₇                  -0.75C₈*S₈
0       0       0       1       0                           0                           (1//16)*(8(C₇^2) - 4(S₇^2)) (1//16)*(8(C₈^2) - 4(S₈^2))

Batoz Tahar

N1      N2      N3      N4      N5                          N6                          N7                          N8
0       0       0       0       - 3/2 S5/l_12               0                           0                           3/2 S_8/l_41  
passt            
0       0       0       0       - 3/4 C_5 S_5               0                           0                           - 3/4 C_8 S_8
passt
1       0       0       0       -(1/4 S_5^2  - 1/2 C_5^2)   0                           0                           -(1/4 S_8^2  - 1/2 C_8^2)
passt
0       0       0       0       3/2 S_5/l_12                - 3/2 S_6/l_23              0                           0
passt
0       0       0       0       - 3/4 C_5 S_5               - 3/4 C_6 S_6               0                           0
passt
0       1       0       0       -(1/4 S_5^2  - 1/2 C_5^2)   -(1/4 S_6^2  - 1/2 C_6^2)   0                           0
passt
0       0       0       0       0                           3/2 S_6/l_23                - 3/2 S_7/l_34              0
passt
0       0       0       0       0                           - 3/4 C_6 S_6               - 3/4 C_7 S_7               0
passt
0       0       1       0       0                           -(1/4 S_6^2  - 1/2 C_6^2)   -(1/4 S_7^2  - 1/2 C_7^2)   0 
passt  
0       0       0       0       0                           0                           3/2 S_7/l_34                - 3/2 S_8/l_41
passt
0       0       0       0       0                           0                           - 3/4 C_7 S_7               - 3/4 C_8 S_8
passt
0       0       0       1       0                           0                           -(1/4 S_7^2  - 1/2 C_7^2)   -(1/4 S_8^2  - 1/2 C_8^2)
passt

ak = - x_ij / l_ij^2                         = - S_k/l_ij 
bk = 3/4 (x_ij y_ij) / l_ij^2                = - 3/4 C_k S_k 
ck = (1/4 x_ij^2 - 1/2 y_ij^2) / l_{ij}^2    = (1/4 S_k^2  - 1/2 C_k^2) 
dk = - y_ij / l_ij^2                         = C_k / l_ij 
ek = -1/2 x_ij^2 + 1/4 y_ij^2 / l_ij^2       = - 1/2 S_k^2 + 1/4 C_k^2

N1      N2      N3      N4      N5                          N6                          N7                          N8
0       0       0       0       3/2 a5                      0                           0                           -3/2 a8
0       0       0       0       b5                          0                           0                           b8
1       0       0       0       -c5                         0                           0                           -c8
0       0       0       0       -3/2 a5                     3/2 a6                      0                           0
0       0       0       0       b5                          b6                          0                           0
0       1       0       0       -c5                         -c6                         0                           0
0       0       0       0       0                           -3/2 a6                     3/2 a7                      0
0       0       0       0       0                           b6                          b7                          0
0       0       1       0       0                           -c6                         -c7                         0   
0       0       0       0       0                           0                           -3/2 a7                     3/2 a8
0       0       0       0       0                           0                           b8                          b7
0       0       0       1       0                           0                           -c7                         -c8

# Überprüfung Hy

Anna Pag
N1      N2      N3      N4      N5                          N6                          N7                          N8
0       0       0       0       (3C₅) / (2l₁₂)              0                           0                           (-3C₈) / (2l₄₁)
-1      0       0       0       (1//16)*(4(C₅^2) - 8(S₅^2)) 0                           0                           (1//16)*(4(C₈^2) - 8(S₈^2))
0       0       0       0       0.75C₅*S₅                   0                           0                           0.75C₈*S₈
0       0       0       0       (-3C₅) / (2l₁₂)             (3C₆) / (2l₂₃)              0                           0
0       -1      0       0       (1//16)*(4(C₅^2) - 8(S₅^2)) (1//16)*(4(C₆^2) - 8(S₆^2)) 0                           0
0       0       0       0       0.75C₅*S₅                   0.75C₆*S₆                   0                           0
0       0       0       0       0                           (-3C₆) / (2l₂₃)             (3C₇) / (2l₃₄)              0
0       0       -1      0       0                           (1//16)*(4(C₆^2) - 8(S₆^2)) (1//16)*(4(C₇^2) - 8(S₇^2)) 0
0       0       0       0       0                           0.75C₆*S₆                   0.75C₇*S₇                   0
0       0       0       0       0                           0                           (-3C₇) / (2l₃₄)             (3C₈) / (2l₄₁)
0       0       0       -1      0                           0                           (1//16)*(4(C₇^2) - 8(S₇^2)) (1//16)*(4(C₈^2) - 8(S₈^2))
0       0       0       0       0                           0                           0.75C₇*S₇                   0.75C₈*S₈  


N1      N2      N3      N4      N5                          N6                          N7                          N8
0       0       0       0       3/2 C_5 / l_12              0                           0                           -3/2 C_8 / l_41
passt
-1      0       0       0       - 1/2 S_5^2 + 1/4 C_5^2     0                           0                           - 1/2 S_8^2 + 1/4 C_8^2
passt
0       0       0       0       3/4 C_5 S_5                 0                           0                           3/4 C_8 S_8
passt
0       0       0       0       -3/2 C_5 / l_12             3/2 C_6 / l_23              0                           0
passt
0       -1      0       0       - 1/2 S_5^2 + 1/4 C_5^2     - 1/2 S_6^2 + 1/4 C_6^2     0                           0
passt
0       0       0       0       3/4 C_5 S_5                 3/4 C_6 S_6                 0                           0
passt
0       0       0       0       0                           -3/2 C_6 / l_23             3/2 C_7 / l_34              0
passt
0       0       -1      0       0                           - 1/2 S_6^2 + 1/4 C_6^2     - 1/2 S_7^2 + 1/4 C_7^2     0   
passt
0       0       0       0       0                           3/4 C_6 S_6                 3/4 C_7 S_7                 0
passt
0       0       0       0       0                           0                           -3/2 C_7 / l_34             3/2 C_8 / l_41
passt
0       0       0       -1      0                           0                           - 1/2 S_7^2 + 1/4 C_7^2     - 1/2 S_8^2 + 1/4 C_8^2
passt
0       0       0       0       0                           0                           3/4 C_7 S_7                 3/4 C_8 S_8
passt


ak = - x_ij / l_ij^2                         = - S_k/l_ij 
bk = 3/4 (x_ij y_ij) / l_ij^2                = - 3/4 C_k S_k 
ck = (1/4 x_ij^2 - 1/2 y_ij^2) / l_{ij}^2    = (1/4 S_k^2  - 1/2 C_k^2) 
dk = - y_ij / l_ij^2                         = C_k / l_ij 
ek = -1/2 x_ij^2 + 1/4 y_ij^2 / l_ij^2       = - 1/2 S_k^2 + 1/4 C_k^2

N1      N2      N3      N4      N5                          N6                          N7                          N8
0       0       0       0       3/2 d5                      0                           0                           -3/2 d8
-1      0       0       0       e5                          0                           0                           e8
0       0       0       0       -b5                         0                           0                           -b8
0       0       0       0       -3/2 d5                     3/2 d6                      0                           0
0       -1      0       0       e5                          e6                          0                           0
0       0       0       0       -b5                         -b6                         0                           0
0       0       0       0       0                           -3/2 d6                     3/2 d7                      0
0       0       -1      0       0                           e6                          e7                          0   
0       0       0       0       0                           -b6                         -b7                         0
0       0       0       0       0                           0                           -3/2 d7                     3/2 d8
0       0       0       -1      0                           0                           e7                          e8
0       0       0       0       0                           0                           -b8                         -b7

# Üerprüfung S und C

Anna Pag
    S₅ = xij[1]/l₁₂
    S₆ = xij[2]/l₂₃
    S₇ = xij[3]/l₃₄
    S₈ = xij[4]/l₄₁

    C₅ = -yij[1]/l₁₂
    C₆ = -yij[2]/l₂₃
    C₇ = -yij[3]/l₃₄
    C₈ = -yij[4]/l₄₁

Batoz Tahar

    C_k = cos(gamma_ij)
    S_k = sin(gamma_ij)