project:
  output-dir: _output

lang: de
number-depth: 3
number-sections: true

format: 
  html:
    theme: cosmo 
    default-image-extension: svg 
  ams-typst: default

chapters:
    # - eidesstattliche-erklaerung.qmd
    # - danksagung.qmd

    # - part: einleitung.qmd
    #   chapters:
    #     - motivation.qmd
    #     - problemstellung.qmd
    #     - zielsetzung-gliederung.qmd

    # - part: grundlagen_FEM.qmd
    #   chapters:
    #     - einfuehrung_FEM.qmd
    #     - historischer-hintergrund.qmd ???
    #     - finite-elemente.qmd
    #           - Definition Finites Element
    #           - Lagrange Element (bilineares Element)
    #           - Bogner-Fox-Schmit
    #           - 

    - part: grundlagen_mech_math.qmd
      chapters:
        - einfuehrung_platten.qmd                       
        - kirchhoffsche-plattentheorie.qmd
    #           - kinematische Gleichungen (Verschiebungsfeld)
    #           - Materialgesetz
    #           - Verzerrungsfeld
    #           - Schnittgrößen
    #           - Gleichgewichtsbeziehungen & Plattengleichung
        - funktionale.qmd    

    # - part: FEM_Plattentragwerke.qmd
    #   chapters:
    #     - Vorbereitungen
    #           - Herleitung_schwacheForm.qmd
    #           - Parametrisierung
    #     - 

    # - part: Umsetzung-in-JULIA-und-Beispiele.qmd
    #   chapters:
    #     - Programmiersprache-Julia.qmd
    #     - Programm.qmd
    #     - Anwendungsbeispiele.qmd
    #     - Verifikation_Vergleich.qmd

    # - part: Zusammenfassung-und-Ausblick.qmd

    # - part: Literatur.qmd