project:
  output-dir: _output

lang: de
number-depth: 3
number-sections: true

filters: 
  - latex-environment.lua
environments: [center]

format: 
  html:
    theme: cosmo 
    default-image-extension: svg 
    mainfont: Times New Roman
  pdf:
    default-image-extension: pdf
    mainfont: Times New Roman
    documentclass: scrreprt
  typst: 
    default-image-extension: svg

  # ams-typst: default




  # chapters:
  #   - eidesstattliche-erklaerung.qmd
  #   - danksagung.qmd

    # - part: einleitung.qmd
    #   chapters:
    #     - motivation.qmd
    #     - problemstellung.qmd
    #     - zielsetzung-gliederung.qmd

    # - part: grundlagen_FEM.qmd
    #   chapters:
    #     - einfhuerung_FEM.qmd
    #     - historischer-hintergrund.qmd ???
    #     - finite-elemente.qmd
    #           - Definition Finites Element
    #           - Lagrange Element (bilineares Element)
    #           - Bogner-Fox-Schmit
    #           - 
   

    # - part: grundlagen_mech_math.qmd
    #   chapters:
    #     - Annahmen_Grundgleichungen_Verschiebungsfeld.qmd
    #     - Verzerrungsfeld.qmd
    #     - Schnittgrößen.qmd
    #     - Gleichgewichtsbeziehungen.qmd

    # - part: FEM_Plattentragwerke.qmd
    #   chapters:
    #     - Herleitung_schwacheForm.qmd
    #     - 
    #     - 

    # - part: Umsetzung-in-JULIA-und-Beispiele.qmd
    #   chapters:
    #     - Programmiersprache-Julia.qmd
    #     - Programm.qmd
    #     - Anwendungsbeispiele.qmd
    #     - Verifikation_Vergleich.qmd

    # - part: Zusammenfassung-und-Ausblick.qmd

    # - part: Literatur.qmd


