project:
  # type: book
  output-dir: _output
  
  #../_build/julia/skript

# project:
#   output-dir: _output

lang: de

book:
  title: "Finite Elemente für Plattentragwerke"
  subtitle: "Theoretische Grundlagen und Programmierung in Julia"
  author: "Anna Paganetty"
  chapters:
      - index.qmd
      - eidesstattliche-erklaerung.qmd
      - danksagung.qmd

      - part: einleitung.qmd
        chapters:
          - motivation.qmd
          - problemstellung.qmd
          - zielsetzung-gliederung.qmd

      - part: grundlagen_FEM.qmd
        chapters:
          - einfuehrung_FEM.qmd
          - finite-elemente.qmd
          - numerische-integration.qmd  
          - einfuehrungsbeispiel.qmd

      - part: grundlagen_mech_math.qmd
        chapters:
          - einfuehrung_platten.qmd                       
          - kirchhoffsche-plattentheorie.qmd
          - funktionale.qmd   
      #   - Definition Finites Element TODO

      # - part: FEM_Plattentragwerke.qmd
      #   chapters:
      #     - Vorbereitungen
      #           - Herleitung_schwacheForm.qmd
      #           - Parametrisierung
      #     - 

      # - part: Umsetzung-in-JULIA-und-Beispiele.qmd
      #   chapters:
      #     - Programmiersprache-Julia.qmd
      #     - Programm.qmd
      #     - Anwendungsbeispiele.qmd
      #     - Verifikation_Vergleich.qmd

      # - part: Zusammenfassung-und-Ausblick.qmd

      # - part: Literatur.qmd
  downloads: 
    - pdf

# format:
#   pdf:
#     documentclass: scrreprt
format:
  ams-typst: default
