project:
  output-dir: _output

book:
  title: "R for Data Science (2e)"
  reader-mode: true

  chapters:
      # - eidesstattliche-erklaerung.qmd
      # - danksagung.qmd

      # - part: einleitung.qmd
      #   chapters:
      #     - motivation.qmd
      #     - problemstellung.qmd
      #     - zielsetzung-gliederung.qmd

      - part: grundlagen_FEM.qmd
        chapters:
          - einfuehrung_FEM.qmd #(inkl. historischer Hintergrund kurz)
      #   - finite-elemente.qmd und deren Basisfunktionen
      #           - Lagrange Element (bilineares Element)
      #           - Bogner-Fox-Schmitt
      #           - Serendipity
      #           - allgemeines Viereck
      #           - C^1-Stetigkeit von Basisfunktionen
      #   - numerische Integration
      #           - Gauß-Integration
      #           - Integration Referenzkoordinaten    
          - einfuehrungsbeispiel.qmd

      - part: grundlagen_mech_math.qmd
        chapters:
          - einfuehrung_platten.qmd                       
          - kirchhoffsche-plattentheorie.qmd
      #           - kinematische Gleichungen (Verschiebungsfeld)
      #           - Materialgesetz
      #           - Verzerrungsfeld
      #           - Schnittgrößen
      #           - Gleichgewichtsbeziehungen & Plattengleichung
          - funktionale.qmd   
      #   - Definition Finites Element TODO

      # - part: FEM_Plattentragwerke.qmd
      #   chapters:
      #     - Vorbereitungen
      #           - Herleitung_schwacheForm.qmd
      #           - Parametrisierung
      #     - 

      # - part: Umsetzung-in-JULIA-und-Beispiele.qmd
      #   chapters:
      #     - Programmiersprache-Julia.qmd
      #     - Programm.qmd
      #     - Anwendungsbeispiele.qmd
      #     - Verifikation_Vergleich.qmd

      # - part: Zusammenfassung-und-Ausblick.qmd

      # - part: Literatur.qmd


format:
  ams-typst: default
