project:
  output-dir: _output

lang: de
number-depth: 3
number-sections: true

filters: 
  - latex-environment
environments: [center]


  # chapters:
  #   - eidesstattliche-erklaerung.qmd
  #   - danksagung.qmd

  #   - part: einleitung.qmd
  #     chapters:
  #       - motivation.qmd
  #       - problemstellung.qmd
  #       - zielsetzung-gliederung.qmd



format: 
  html: 
    default-image-extension: svg 
  pdf:
    default-image-extension: pdf


    # - part: Grundlagen_FEM.qmd
    #   chapters:

    # - part: Grundlange_mech_math.qmd
    #   chapters:
    #     - Annahmen_Grundgleichungen_Verschiebungsfeld.qmd
    #     - Verzerrungsfeld.qmd
    #     - Schnittgrößen.qmd
    #     - Gleichgewichtsbeziehungen.qmd

    # - part: FEM_Plattentragwerke.qmd
    #   chapters:
    #     - Herleitung_starkeForm.qmd
    #     - Herleitung_schwacheForm.qmd # beide wege

    # - part: Programmierung-und-Beispiele.qmd
    #   chapters:
    #     - Programmiersprache-Julia.qmd
    #     - Programm.qmd
    #     - Anwendungsbeispiele.qmd
    #     - Verifikation_Vergleich.qmd
