# physikalische und Referenzkoordinaten

TODO:   Darstellung Referenzelement & physikalische Element

Bei den folgenden Formeln wird _ein_ Element betrachtet, daher wird in keiner Formel ein Index für das Element genutzt.
Sei $(\xi,\eta)$ ein beliebiger Punkt auf dem Referenzelement, so werden durch

$$
x(\xi,\eta) = F_{x}(\xi,\eta) = \sum_{i=1}^n N_i(\xi,\eta) \cdot x_i  \quad\mbox{für}\quad i = 1,..,4
$$ {#eq-black-scholes}
und 
$$
y(\xi,\eta) = F_{y}(\xi,\eta) = \sum_{i=1}^n N_i(\xi,\eta) \cdot y_i^e \quad\mbox{für}\quad i = 1,..,4
$$ {#eq-black-scholes}

die physikalischen Koordinaten auf dem Element $\Omega_e$ beschrieben. Die vier linearen Formfunktionen $N_i$ des quadratischen Referenzelements, dargestellt in Abbildung ..., 
$$
\begin{align}
N_1(\xi,\eta) &= \frac{1}{4} \cdot (1-\xi) \cdot (1-\eta), 
&N_2(\xi,\eta) = \frac{1}{4} \cdot (1+\xi) \cdot (1-\eta), \\
N_3(\xi,\eta) &= \frac{1}{4} \cdot (1+\xi) \cdot (1+\eta), 
&N_4(\xi,\eta) = \frac{1}{4} \cdot (1-\xi) \cdot (1+\eta) \\
\end{align}
$$ {#eq-black-scholes}
definiert.


und den Koordinaten des physikalischen Elements $x_i^e$ und $y_i^e$

$$
\begin{align}
x_i^e = \left[ \begin{array}{center} 
x_1^e \\
x_2^e \\
x_3^e \\
x_4^e 
\end{array}\right] 
&&y_i^e = \left[ \begin{array}{center} 
y_1^e \\
y_2^e \\
y_3^e \\
y_4^e 
\end{array}\right]. \\
\end{align}
$$ {#eq-black-scholes}

Die Ableitungen der Umrechnungsausdrücke sind 

$$
\begin{align}
F_{x}^{e'}(\xi,\eta) = \frac{\partial F_{x}^e(\xi,\eta)}{\partial \xi}
&&F_{x}^{e'}(\xi,\eta) = \frac{\partial F_{x}^e(\xi,\eta)}{\partial \eta}\\
F_{y}^{e'}(\xi,\eta) = \frac{\partial F_{y}^e(\xi,\eta)}{\partial \xi}
&&F_{y}^{e'}(\xi,\eta) = \frac{\partial F_{y}^e(\xi,\eta)}{\partial \eta}.
\end{align}
$$ {#eq-black-scholes}

Zur Umrechnung der physikalischen Koordinaten $(x,y)$ zu den Referenzkoordinaten $(\xi,\eta)$ werden die Umkehrfunktionen von $F_{xe}(\xi,\eta)$ und $F_{ye}(\xi,\eta)$ gebildet.

$$
\begin{align}
        &(x,y) \to \xi(x,y) = F_{x}^{e-1}(x,y) \\
        &(x,y) \to \eta(x,y) = F_{y}^{e-1}(x,y) 
\end{align}
$$ {#eq-black-scholes}

Die dementsprechenden Ableitungen sind:

$$
\begin{align}
F_{x}^{e-1'}(x,y) = \frac{\partial F_{x}^{e-1}(x,y)}{\partial \xi}
&&F_{x}^{e-1'}(x,y) = \frac{\partial F_{x}^{e-1}(x,y)}{\partial \eta}\\
F_{y}^{e-1'}(x,y) = \frac{\partial F_{y}^{e-1}(x,y)}{\partial \xi}
&&F_{y}^{e-1'}(x,y) = \frac{\partial F_{y}^{e-1}(x,y)}{\partial \eta}.
\end{align}
$$ {#eq-black-scholes}

Betrachten wir das erste Element eines Finite Elemente Netzes $\Omega_1$. Die oben bereits beschriebenen linearen Formfunktionen sind in Abb. ... dargestellt.

TODO: Beschriftung der Funktionen!
```{julia}
# #| echo: false
# #| output: true
# #| warning: false
# include("../src/setup.jl")
# V = [ -1 1 1 -1; -1 -1 1 1]
# L = lagrangeelement(V)
# fplot3d(L)
```

Die Formfunktionen auf dem Element $\Omega_1$ $(e = 1)$ werden nachfolgend $\varphi_i(x,y)$ mit $i = 1,...,4$.

$$
\begin{align}
\varphi_1(x,y)  = N_1(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y)) \\
\varphi_2(x,y)  = N_2(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y)) \\
\varphi_3(x,y)  = N_3(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y)) \\
\varphi_4(x,y)  = N_4(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y))
\end{align}
$$ {#eq-black-scholes}

Zur späteren Berechnung der Elementsteifigkeitsmatrix, werden die Ableitungen dieser Funktionen gebraucht. Dazu wird die Kettenregel genutzt. Nachfolgend wird an der Funktion $\varphi_1(x,y)$ die Vorgehensweise gezeigt.

$$
\begin{align}
\frac{\partial \varphi_1(x,y)}{\partial x} = 
\left[ \begin{array}{center}    
\frac{\partial N_1(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y))}{\partial F_{x1}^{-1}(x,y)} &
\frac{\partial N_1(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y))}{\partial F_{y1}^{-1}(x,y)}
\end{array}\right]
\left[ \begin{array}{center} 
\frac{\partial F_{x1}^{-1}(x,y)}{\partial x} \\
\frac{\partial F_{y1}^{-1}(x,y)}{\partial x}
\end{array}\right] 
\end{align}
$$ {#eq-black-scholes}

$$
\begin{align}
\frac{\partial \varphi_1(x,y)}{\partial y} = 
\left[ \begin{array}{center}    
\frac{\partial N_1(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y))}{\partial F_{x1}^{-1}(x,y)} &
\frac{\partial N_1(F_{x1}^{-1}(x,y),F_{y1}^{-1}(x,y))}{\partial F_{y1}^{-1}(x,y)}
\end{array}\right]
\left[ \begin{array}{center} 
\frac{\partial F_{x1}^{-1}(x,y)}{\partial y} \\
\frac{\partial F_{y1}^{-1}(x,y)}{\partial y}
\end{array}\right] 
\end{align}
$$ {#eq-black-scholes}

einfacher geschrieben mit 

$$
\begin{align}
F_{x1}^{-1}(x,y) = \xi(x,y) \\
F_{y1}^{-1}(x,y) = \eta(x,y) \\
\end{align}
$$ {#eq-black-scholes}
(siehe Gleichung (5))

$$
\begin{align}
\frac{\partial \varphi_1(x,y)}{\partial x} &=  
\frac{\partial N_1(\xi(x,y),\eta(x,y))}{\partial \xi(x,y)}
\cdot \frac{\partial \xi(x,y)}{\partial x}
+
\frac{\partial N_1(\xi(x,y),\eta(x,y))}{\partial \eta(x,y)}
\cdot \frac{\partial \eta(x,y)}{\partial x}
\end{align}
$$ {#eq-black-scholes}

$$
\begin{align}
\frac{\partial \varphi_1(x,y)}{\partial y} &=   
\frac{\partial N_1(\xi(x,y),\eta(x,y))}{\partial \xi(x,y)}
\cdot \frac{\partial \xi(x,y)}{\partial y}
+
\frac{\partial N_1(\xi(x,y),\eta(x,y))}{\partial \eta(x,y)}
\cdot \frac{\partial \eta(x,y)}{\partial y}
\end{align}
$$ {#eq-black-scholes}

Zusammengefasst ergibt sich:

$$ 
\left[ \begin{array}{center} 
\frac{\partial \varphi_1(x,y)}{\partial x} \\
\frac{\partial \varphi_1(x,y)}{\partial y}
\end{array}\right]
= 
\underbrace{\left[ \begin{array}{center} 
\frac{\partial \xi(x,y)}{\partial x} & \frac{\partial \eta(x,y)}{\partial x} \\
\frac{\partial \xi(x,y)}{\partial y} & \frac{\partial \eta(x,y)}{\partial y} 
\end{array}\right]}_{\mathbf{J}}
\left[ \begin{array}{center} 
\frac{\partial N_1(\xi(x,y),\eta(x,y))}{\partial \xi(x,y)} \\
\frac{\partial N_1(\xi(x,y),\eta(x,y))}{\partial \eta(x,y)}
\end{array}\right]
$$ {#eq-black-scholes}


__Ab hier muss noch überarbeitet werden __

## 2D

$$
\hat{Q} := {(\xi,\eta) \in \mathbb{R}^2; \xi = [-1,1], \eta = [-1,1]}
$$

Um die Stefigkeitsmatrix des DKQ Elementes herzuleiten ist es notwendig die Formfunktionen $N_i$, bezogen auf das Referenzelement $\hat{Q}$, nach $x$ und $y$ abzuleiten. 
Hierzu müssen die Funktionen $N_i$ von den Referenzkoordinaten $\xi$ und $\eta$ zu den physikalischen Koordinaten $x$ und $y$ transformiert werden. 

Um die Ableitung der Funktionen $N_i$ nach $\xi$ und $\eta$ zu berechnen wird die Kettenregel genutzt.


$$ 
\frac{\partial N_i}{\partial \xi} = \frac{\partial N_i}{\partial x} \cdot \frac{\partial x}{\partial \xi} + \frac{\partial N_i}{\partial y} \cdot \frac{\partial y}{\partial \xi} 
$$ {#eq-black-scholes}

$$ 
\frac{\partial N_i}{\partial \eta} = \frac{\partial N_i}{\partial x} \cdot \frac{\partial x}{\partial \eta} + \frac{\partial N_i}{\partial \eta} \cdot \frac{\partial y}{\partial \eta}  
$$ {#eq-black-scholes}

oder:

$$ 
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial \xi} \\
\frac{\partial N_i}{\partial \eta}
\end{array}\right]
= 
\underbrace{\left[ \begin{array}{center} 
\frac{\partial x}{\partial \xi} & \frac{\partial y}{\partial \xi} \\
\frac{\partial x}{\partial \eta} & \frac{\partial y}{\partial \eta}
\end{array}\right]}_{\mathbf{J}}
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial x} \\
\frac{\partial N_i}{\partial y}
\end{array}\right]
$$ {#eq-black-scholes}

__Definition _Jacobi-Matrix_ (benannt nach Carl Gustav Jacob Jacobi 1804-1851) oder _Funktionalmatrix___

Seien die Funktionen $N_i$ im Punkt $(\xi,\eta)$ differenzierbar, so sind sie auch an der selben Stelle nach den Veränderlichen $x$ und $y$, mit Hilfe der Jacobi-Matrix $\mathbf{J}$, partiell differenzierbar. Folglich kann die Ableitung der Funktionen $N_i$ nach $x$ und $y$ mit Hilfe der inversen Jacobi-Matrix $\mathbf{J^{-1}}$ berechnet werden. 

<!-- Toutes les expressions qui implique des dérivées de u en x,y sont transformées en dérivées en xi, eta grâce à la matrice de transformation dite matrice jacobienne.
+
Die Funktion f sei im Punkt xi differenzierbar, dann ist sie auch an der Stelle xi nach allen Veränderlichen (x und y)  partiell differenzierbar -->

$$ 
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial x} \\
\frac{\partial N_i}{\partial y}
\end{array}\right]
= 
\underbrace{\left[ \begin{array}{center} 
\frac{\partial x}{\partial \xi} & \frac{\partial y}{\partial \xi} \\
\frac{\partial x}{\partial \eta} & \frac{\partial y}{\partial \eta}
\end{array}\right]^{-1}}_{\mathbf{J^{-1}}}
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial \xi} \\
\frac{\partial N_i}{\partial \eta}
\end{array}\right]
$$

__Berechnung der Jacobi-Matrix__

Die Einträge der Transformationsmatrix für den zweidimensionalen Raum werden nachfolgend berechnet.
$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
J_{11} & J_{12} \\
J_{21} & J_{22}
\end{array}\right] \\
\\
\mathbf{J^{-1}} &= \frac{1}{det(\mathbf{J})}
\left[ \begin{array}{center} 
J_{22} & -J_{12} \\
-J_{21} & J_{11}
\end{array}\right] \\
\\
det(\mathbf{J}) &= J_{11}J_{22} - J_{12}J_{21}
\end{align}
$$
Die Formfunktionen zur Berechnung der Transformationsmatrix im zweidimensionalen Raum, sind die Funktionen des Bilinearen Viereckelements 

<!-- 
$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
\sum_{i=1}^4 \frac{ N_i(\xi,\eta)}{\partial \xi} \cdot x_i^e & \sum_{i=1}^4 \frac{N_i(\xi,\eta)}{\partial \xi} \cdot y_i^e \\
\sum_{i=1}^4 \frac{ N_i(\xi,\eta)}{\partial \eta} \cdot x_i^e & \sum_{i=1}^4 \frac{N_i(\xi,\eta)}{\partial \eta} \cdot y_i^e
\end{array}\right] 
\end{align}
$$ 
-->


$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
\frac{N_1}{\partial \xi}   & \frac{N_2}{\partial \xi}   & \frac{N_3}{\partial \xi}   & \frac{N_4}{\partial \xi} \\
\frac{N_1}{\partial \eta}  & \frac{N_2}{\partial \eta}  & \frac{N_3}{\partial \eta}  & \frac{N_4}{\partial \eta}
\end{array}\right]
\left[ \begin{array}{center} 
x_1^e & y_1^e \\
x_2^e & y_2^e \\
x_3^e & y_3^e \\
x_4^e & y_4^e 
\end{array}\right] \\
\\
&=
\frac{1}{4}
\left[ \begin{array}{center} 
-(1-\eta) & (1-\eta) & (1+\eta) & -(1+\eta)  \\
-(1-\xi)  & -(1+\xi) & (1+\xi)  & (1-\xi) 
\end{array}\right]
\left[ \begin{array}{center} 
x_1^e & y_1^e \\
x_2^e & y_2^e \\
x_3^e & y_3^e \\
x_4^e & y_4^e 
\end{array}\right]
\end{align}
$$

Es ergeben sich die Komponenten der Jacobi-Matrix

$$
\begin{align}
J_{11}  &= \frac{1}{4} \cdot (-x_1^e + x_2^e + x_3^e - x_4^e + \eta (x_1^e - x_2^e + x_3^e - x_4^e)) \\
J_{12}  &= \frac{1}{4} \cdot (-y_1^e + y_2^e + y_3^e - y_4^e + \eta (y_1^e - y_2^e + y_3^e - y_4^e)) \\
J_{21}  &= \frac{1}{4} \cdot (-x_1^e - x_2^e + x_3^e + x_4^e + \xi (x_1^e - x_2^e + x_3^e - x_4^e)) \\
J_{22}  &= \frac{1}{4} \cdot (-y_1^e - y_2^e + y_3^e + y_4^e + \xi (y_1^e - y_2^e + y_3^e - y_4^e)) \\
\end{align}
$$

und die Komponenten der inversen Transformationsmatrix
$$ 
\begin{align}
j_{11} &= \frac{1}{det(\mathbf{J})} \cdot J_{22}    &j_{12} = \frac{1}{det(\mathbf{J})} \cdot J_{12} \\
j_{21} &= \frac{1}{det(\mathbf{J})} \cdot J_{21}    &j_{22} = \frac{1}{det(\mathbf{J})} \cdot J_{11} \\
\end{align}
$$
$$
det(\mathbf{J}) =   \frac{1}{8} \cdot (y_{42}^e x_{31}^e - y_{31}^e x_{42}^e) +
                    \frac{\xi}{8} \cdot (y_{34}^e x_{21}^e - y_{21}^e x_{34}^e) +
                    \frac{\eta}{8} \cdot (y_{41}^e x_{32}^e - y_{32}^e x_{41}^e)
$$
