# Transformation der Ableitungsoperatoren

## Generelles

Ziel der Transformation $\tau$ ist, die physikalischen Koordinaten $x$ und $y$ in die Koordinaten des Referenzelements $\xi$ und $\eta$ umzuwandeln.Sei $(\xi,\eta)$ ein beliebiger Punkt auf dem Referenzelement, so werden durch $x(\xi,\eta)$ und $y(\xi,\eta)$ die dementsprechenden physikalischen Koordinaten beschrieben.

$$
\begin{align}
\tau :  &(\xi,\eta) \to x(\xi,\eta) = \sum_{i=1}^n N_i^e(\xi,\eta) \cdot x_i^e\\
        &(\xi,\eta) \to y(\xi,\eta) = \sum_{i=1}^n N_i^e(\xi,\eta) \cdot y_i^e
\end{align}
$$

Alle Formulierungen, welche eine Ableitung nach $x$ und $y$ beinhalten werden transformiert in Ableitungen nach $\xi$ und $\eta$, mit Hilfe der Transformationsmatrix, der sogenannten Jacobi-Matrix $\mathbf{J}$.

<!-- ## 1D

Betrachtet wird ein eindimensionales Element $I$, welches auf das Referenzelement $Î$ transformiert wird. 
$$
\begin{align}
I &:= {(x) \in \mathbb{R}; x = [x_1^e,x_2^e]} \\
\\
Î &:= {(\xi) \in \mathbb{R}; \xi = [-1,1]}
\end{align}
$$

Sei $\xi$ ein belibiger Punkt auf dem Referenzelement, so wird wird durch $F(\xi)$ die dementsprechende physikalische Koordinate beschrieben.

$$
F_e(\xi) = \sum_{i=1}^n N_i^e(\xi) \cdot x_i^e
$$

Die Funktionen $N_i$ für das lineare 2-Knoten-Element haben die folgende Form:
$$
\begin{align}
N_1^e(\xi) &= \frac{1-\xi}{2} \\
\\
N_2^e(\xi) &= \frac{1+\xi}{2}
\end{align}
$$

Jacobi Matrix
$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
\frac{\partial x}{\partial \xi}
\end{array}\right] = 
\left[ \begin{array}{center} 
\frac{1}{2} \cdot (x_2^e - x_1^e)
\end{array}\right]\\
\end{align}
$$ 
-->

## 2D

$$
\hat{Q} := {(\xi,\eta) \in \mathbb{R}^2; \xi = [-1,1], \eta = [-1,1]}
$$

Um die Stefigkeitsmatrix des DKQ Elementes herzuleiten ist es notwendig die Formfunktionen $N_i$, bezogen auf das Referenzelement $\hat{Q}$, nach $x$ und $y$ abzuleiten. Hierzu müssen die Funktionen $N_i$ von den Referenzkoordinaten $\xi$ und $\eta$ zu den physikalischen Koordinaten $x$ und $y$ transformiert werden. 

Um die Ableitung der Funktionen $N_i$ nach $\xi$ und $\eta$ zu berechnen wird die Kettenregel genutzt.

$$ \frac{\partial N_i}{\partial \xi} = \frac{\partial N_i}{\partial x} \cdot \frac{\partial x}{\partial \xi} + \frac{\partial N_i}{\partial y} \cdot \frac{\partial y}{\partial \xi}$$
$$ \frac{\partial N_i}{\partial \eta} = \frac{\partial N_i}{\partial x} \cdot \frac{\partial x}{\partial \eta} + \frac{\partial N_i}{\partial \eta} \cdot \frac{\partial y}{\partial \eta}  $$

oder:

$$ 
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial \xi} \\
\frac{\partial N_i}{\partial \eta}
\end{array}\right]
= 
\underbrace{\left[ \begin{array}{center} 
\frac{\partial x}{\partial \xi} & \frac{\partial y}{\partial \xi} \\
\frac{\partial x}{\partial \eta} & \frac{\partial y}{\partial \eta}
\end{array}\right]}_{\mathbf{J}}
\cdot
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial x} \\
\frac{\partial N_i}{\partial y}
\end{array}\right]
$$

$\mathbf{J}$ beschreibt die Jacobi-Matrix, welche für die geometrische Transformation notwendig ist. Folglich kann die Ableitung der Funktionen $N_i$ nach $x$ und $y$ mit Hilfe der inversen Jacobi-Matrix $\mathbf{J^{-1}}$ berechnet werden.

$$ 
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial x} \\
\frac{\partial N_i}{\partial y}
\end{array}\right]
= 
\underbrace{\left[ \begin{array}{center} 
\frac{\partial x}{\partial \xi} & \frac{\partial y}{\partial \xi} \\
\frac{\partial x}{\partial \eta} & \frac{\partial y}{\partial \eta}
\end{array}\right]^{-1}}_{\mathbf{J^{-1}}}
\cdot
\left[ \begin{array}{center} 
\frac{\partial N_i}{\partial \xi} \\
\frac{\partial N_i}{\partial \eta}
\end{array}\right]
$$

__Berechnung der Jacobi-Matrix__

Die Einträge der Transformationsmatrix für den zweidimensionalen Raum werden nachfolgend berechnet.
$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
J_{11} & J_{12} \\
J_{21} & J_{22}
\end{array}\right] \\
\\
\mathbf{J^{-1}} &= \frac{1}{det(\mathbf{J})}
\left[ \begin{array}{center} 
J_{22} & -J_{12} \\
-J_{21} & J_{11}
\end{array}\right] \\
\\
det(\mathbf{J}) &= J_{11}J_{22} - J_{12}J_{21}
\end{align}
$$
Die Formfunktionen zur Berechnung der Transformationsmatrix im zweidimensionalen Raum, sind die Funktionen des Bilinearen Viereckelements 

$$
\begin{align}
N_1 &= \frac{1}{4} \cdot (1-\xi) \cdot (1-\eta) \\
N_2 &= \frac{1}{4} \cdot (1+\xi) \cdot (1-\eta) \\
N_3 &= \frac{1}{4} \cdot (1+\xi) \cdot (1+\eta) \\
N_4 &= \frac{1}{4} \cdot (1-\xi) \cdot (1+\eta) \\
\end{align}
$$

<!-- 
$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
\sum_{i=1}^4 \frac{ N_i(\xi,\eta)}{\partial \xi} \cdot x_i^e & \sum_{i=1}^4 \frac{N_i(\xi,\eta)}{\partial \xi} \cdot y_i^e \\
\sum_{i=1}^4 \frac{ N_i(\xi,\eta)}{\partial \eta} \cdot x_i^e & \sum_{i=1}^4 \frac{N_i(\xi,\eta)}{\partial \eta} \cdot y_i^e
\end{array}\right] 
\end{align}
$$ 
-->


$$
\begin{align}
\mathbf{J} &=
\left[ \begin{array}{center} 
\frac{N_1}{\partial \xi}   & \frac{N_2}{\partial \xi}   & \frac{N_3}{\partial \xi}   & \frac{N_4}{\partial \xi} \\
\frac{N_1}{\partial \eta}  & \frac{N_2}{\partial \eta}  & \frac{N_3}{\partial \eta}  & \frac{N_4}{\partial \eta}
\end{array}\right]
\cdot
\left[ \begin{array}{center} 
x_1^e & y_1^e \\
x_2^e & y_2^e \\
x_3^e & y_3^e \\
x_4^e & y_4^e 
\end{array}\right] \\
\\
&=
\frac{1}{4}
\left[ \begin{array}{center} 
-(1-\eta) & (1-\eta) & (1+\eta) & -(1+\eta)  \\
-(1-\xi)  & -(1+\xi) & (1+\xi)  & (1-\xi) 
\end{array}\right]
\cdot
\left[ \begin{array}{center} 
x_1^e & y_1^e \\
x_2^e & y_2^e \\
x_3^e & y_3^e \\
x_4^e & y_4^e 
\end{array}\right]
\end{align}
$$

Es ergeben sich die Komponenten der Jacobi-Matrix

$$
\begin{align}
J_{11}  &= \frac{1}{4} \cdot (-x_1^e + x_2^e + x_3^e - x_4^e + \eta (x_1^e - x_2^e + x_3^e - x_4^e)) \\
J_{12}  &= \frac{1}{4} \cdot (-y_1^e + y_2^e + y_3^e - y_4^e + \eta (y_1^e - y_2^e + y_3^e - y_4^e)) \\
J_{21}  &= \frac{1}{4} \cdot (-x_1^e - x_2^e + x_3^e + x_4^e + \xi (x_1^e - x_2^e + x_3^e - x_4^e)) \\
J_{22}  &= \frac{1}{4} \cdot (-y_1^e - y_2^e + y_3^e + y_4^e + \xi (y_1^e - y_2^e + y_3^e - y_4^e)) \\
\end{align}
$$

und die Komponenten der inversen Transformationsmatrix
$$ 
\begin{align}
j_{11} &= \frac{1}{det(\mathbf{J})} \cdot J_{22}    &j_{12} = \frac{1}{det(\mathbf{J})} \cdot J_{12} \\
j_{21} &= \frac{1}{det(\mathbf{J})} \cdot J_{21}    &j_{22} = \frac{1}{det(\mathbf{J})} \cdot J_{11} \\
\end{align}
$$
$$
det(\mathbf{J}) =   \frac{1}{8} \cdot (y_{42}^e x_{31}^e - y_{31}^e x_{42}^e) +
                    \frac{\xi}{8} \cdot (y_{34}^e x_{21}^e - y_{21}^e x_{34}^e) +
                    \frac{\eta}{8} \cdot (y_{41}^e x_{32}^e - y_{32}^e x_{41}^e)
$$
