## Vorbereitung {#sec-vorbereitung}

### Herleitung der schwachen Form {#sec-schwache-form}

Die Basis der Finite Element Methode bildet die schwache Form des Problems. Ausgehend von der starken Form, der Differentialgleichung (Gleichung... ) der Kirchhoffplatte, vereinfacht ausgedrückt durch den Laplace-Operator,

$$
D \cdot \Delta \Delta w = q 
$$ {#eq-diffgl-laplace}

<!-- 
$$
\Delta w = \frac{\partial^2 w}{\partial x^2} + \frac{\partial^2 w}{\partial y^2}
$$ {#eq-diffgl-laplace} 
-->

ergibt sich nach Multiplikation mit der Testfunktion $\delta w : \Omega \to \mathbb{R}$

$$
D \cdot  (w_{,xxxx} \cdot \delta w 
+ 2 \cdot w_{,xxyy} \cdot \delta w 
+ \cdot w_{,yyyy}\cdot \delta w)
=  q \cdot \delta w .
$$ {#eq-diffgl-testfunk}

Nach der Integration beider Seiten über die Fläche $\Omega$ und durch Anwendung der Summenregel für Integrale folgt
$$
D \cdot [ \underbrace{\int_{\Omega} w_{,xxxx} \cdot \delta w \quad d \Omega}_{\text{1. Summand}} + \underbrace{\int_{\Omega} 2 \cdot w_{,xxyy} \cdot \delta w \quad d \Omega}_{\text{2. Summand}} + \underbrace{\int_{\Omega} w_{,yyyy}\cdot \delta w \quad d \Omega}_{\text{3. Summand}}] = \int_{\Omega} q \cdot \delta w \quad d \Omega.
$$ {#eq-diffgl-testfunk-integral}

Die drei Summanden auf der linke Seite der Gleichung werden zweifach partiell integriert. Zudem wird angenommen, dass alle Rantherme, also Momente und Querkräfte an dem Rand des Gebiets $\Omega$, $=0$. Dadurch ergeben sich die Teilergebnisse für 

$$
\begin{flalign}
&\text{den 1. Summanden} \\
\\
&\int_{\Omega} w_{,xxxx} \cdot \delta w \quad d \Omega
&&=
- \int_{\Omega} \delta w_{,xx} \cdot w_{,xx} \quad d \Omega \\
\\
\\
&\text{den 2. Summanden} \\
\\
&\int_{\Omega} 2 \cdot w_{,xxyy} \cdot \delta w \quad d \Omega
&&= \int_{\Omega} 2 \cdot \delta w_{,xy} \cdot w_{,xy} \quad d \Omega \\
\\
\\
&\text{und den 3. Summanden} \\
\\
&\int_{\Omega} w_{,yyyy} \cdot \delta w \quad d \Omega
&&=
- \int_{\Omega} \delta w_{,yy} \cdot w_{,yy} \quad d \Omega
\end{flalign}
$$


Das Zusammenführen der Teilergebnisse ergibt das nachfolgend dargestellte Variationsproblem für die Kirchhoffplatte.

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}
*Variations Problem (V)* \

Gesucht ist die Funktion $w:\Omega \to \mathbb{R}$, sodass 
\
\
$$
\begin{align}
\int_{\Omega} D (w_{,xx} \delta w_{,xx} + 2 w_{,xy} \delta w_{,xy} + w_{,yy} \delta w_{,yy} ) \quad d \Omega 
= \int_{\Omega} q \cdot \delta w \quad d \Omega
\end{align}
$$ {#eq-variationsproblem}

\
<!-- 
__Eigentlich RICHTIG__
$$
\begin{align}
\int_{\Omega}  D (1+\nu) \cdot (\frac{\partial^2 w}{\partial x^2} \cdot \frac{\partial^2 \delta w}{\partial x^2} + 2 \cdot \frac{\partial w}{\partial x \partial y} \cdot \frac{\partial \delta w}{\partial x \partial y} + \frac{\partial^2 w}{\partial y^2} \cdot \frac{\partial^2 \delta w}{\partial y^2} \quad d \Omega) \\ 
= \int_{\Omega} q \cdot \delta w \quad d \Omega
\end{align}
$$ {#eq-variationsproblem-2}
 -->
für jede (fast) beliebige Testfunktion $\delta w:\Omega \to \mathbb{R}$.

:::

Das Variationsproblem lässt sich mit Hilfe von Funktionalen in eine generelle Form bringen. Die linke Seite der @eq-variationsproblem wird als Bilinearform $a:V \times V \to \mathbb{R}$ und die rechte Seite als Linearform $b:V \to \mathbb{R}$ definiert.

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

*Abstraktes Variationsproblem* 
\
\
Gesucht ist die Funktion $w \in V$, sodass 
$$
a(w, \delta w)= b(\delta w)
$${#eq-abstraktes-variationsproblem}

für alle Testfunktionen $\delta w \in V$

:::

Diese generelle Form des Problems wird für eine Vielzahl von Anwendungen genutzt. Im Fall der Kirchhoffplatte ist die Bilinearform 

$$ 
\begin{align}
&a(\mathbf{w}, \mathbf{\delta w}) &&= \int_{\Omega} D (w_{,xx} \delta w_{,xx} + 2 w_{,xy} \delta w_{,xy} + w_{,yy} \delta w_{,yy} ) \quad d \Omega \\
&\text{mit} \qquad
D &&= \frac{Eh^3}{12(1+\nu^2)} \qquad \text{(isotrope Plattensteifigkeit)}
\end{align}
$$ {#eq-bilinearform}

und die Linearform

$$ 
b(\mathbf{\delta w}) = \int_{\Omega} q \cdot \delta w \quad d \Omega.
$$ {#eq-linearform}

Sowohl $\mathbf{w}$ als auch $\mathbf{\delta w}$ sind als Tupel von Funktionen zu verstehen.

### Approximation von Funktionen {#sec-approximation-funktionen}

Die FEM-Lösung basiert im wesentlichen auf zwei Ideen:

1. Konstruieren einer Näherungslösung durch die Kombination von vordefinierten Funktionen
2. Funktionen stückweise definieren auf sogenannten Elementen

Bei der schubstarren Platte nach Kirchhoff wird die Verformung durch $w$ beschrieben. Die Verdrehungen $\theta_x$ und $\theta_y$ werden durch die Ableitung der Verformung beschrieben. Für die Näherungslösung der Verformung werden Basisfunktionen $\varphi_1, \varphi_2,...,\varphi_N$ gewählt, sodass $w_h$ durch die Funktion
$$
\begin{align}
&w_h(x,y) = \varphi_1(x,y) \cdot \hat{w}_1 +  \varphi_2(x,y) \cdot \hat{w}_2 + ... + \varphi_N(x,y) \cdot \hat{w}_N = \sum_{i=1}^N \varphi_i(x,y) \cdot \hat{w}_i 
\end{align}
$${#eq-linearkombination-platte}

approximiert wird. Das ursprüngliche Problem, eine Lösungsfunktionen zu finden, ist jetzt ersetzt worden durch das Problem, reele Zahlen $\hat{w}_1, \hat{w}_2,...,\hat{w}_N$ zu finden. Die Summe in @eq-linearkombination-platte versteht sich als Linearkombination von Basisfunktionen. Bei der Definition des Abstrakten Variationsproblems wurde bereits der Raum $V$ eingeführt, welcher die Menge aller Funktionen auf dem Gebiet $\Omega$ beschreibt. Der Raum $V$ ist unendlich dimensional. Die Menge aller möglichen Linearkombination von $\varphi_1, \varphi_2,...,\varphi_N$ ist der endlich dimensionale Vektorraum 

$$
\begin{align}
&V_h = Lin(\varphi_1,\varphi_2,...,\varphi_N) = \{ \sum_{i=1}^N \varphi_i \cdot \hat{w}_i \vert \hat{w}_i \in \mathbb{R} \}, \\
% &V_h \subset V
\end{align}
$${#eq-subspace}

wobei $V_h$ ein Unterraum von $V$ ist und $N$ die Dimension des Raums $V_h$. Die Funktionen $\varphi_i$ sind die Elemente des Vektorraums $V_h$. Das sich daraus ergebende Problem wird _abstracktes, diskretes Variationsproblem_ bezeichnet.

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

*Abstraktes, diskretes Variationsproblem* 
\
\
Gesucht ist eine Funktion $w_h \in V_h$, sodass 
$$
a(w_h, \delta w_h)= b(\delta w_h) \quad \forall \quad \delta w_h \in V_h
$${#eq-abstraktes-diskretes-variationsproblem}

:::

Die zweite Idee basiert darauf, dass das gesamte System in mehrere Elemente aufgeteilt wird und die Funktionen elementweise definiert werden. Das Berechnungsgebiet $\Omega$, in diesem Fall die Platte, wird in die Elemente $\Omega_e, e = 1,...,N_e$ unterteilt. In dieser Arbeit wird sich auf viereckige Plattenelemente beschränkt, sodass jedes Element mindestens vier Knoten hat, je nach Elementansatz aber auch acht oder mehr Knoten haben kann (siehe @sec-finite-elemente). Die Basisfunktionen $\varphi_1, \varphi_2,...,\varphi_N$ werden elementweise definiert. Die gesuchten reelen Zahlen $\hat{w}_i \in \mathbb{R}$ werden Freiheitsgrade bzw. im englischen _degrees of freedom_ (abgekürzt DOF) bezeichnet.

### numerische Lösung {#sec-numerische-loesung}

Die Gleichung des abstrakten diskreten Variationsproblem gilt für alle Testfunktionen $\delta w_h$. Für die numerische Lösung des Problems
wird dieses durch $N$ Gleichungen mit $w_h$ als Unbekannte ersetzt. Dazu wird die Linearkombination

$$
\delta w_h = \sum_{i = 1}^N \varphi_i \cdot \delta \hat{w}_i
$$

eingesetzen in @eq-abstraktes-diskretes-variationsproblem. Durch die in @sec-funktionale besprochenen Funktionale, angewandt auf das vorliegenden Problem ist festzustellen, dass die Sätze 

::: {.block fill="luma(230)" inset="8pt" radius="4pt"}

$$
\begin{align}
a(w_h, \delta w_h) &= b(\delta w_h) \qquad &&\forall \delta w_h \in V_h \\
a(w_h, \Sigma_{i = 1}^N \varphi_i \cdot \delta \hat{w}_i)&= b(\Sigma_{i = 1}^N \varphi_i \cdot \delta \hat{w}_i) \quad &&\forall \quad \delta w_h \in V_h \\
a(w_h, \varphi_i)&= b(\varphi_i) \qquad &&i = 1,...,N
\end{align}
$${#eq-03}

:::

alle äquivalent sind. 

Im zweiten Schritt wird 

$$
w_h = \sum_{j = 1}^N \varphi_j \cdot \hat{w}_j
$$

eingesetzt in die lezten Gleichung von @eq-03, dessen Ergebniss, nach gleicher Vorhergehensweise wir oben, 

$$
\sum_{j = 1}^N \underbrace{a(\varphi_j, \varphi_i)}_{k_{ij}} \cdot \hat{w}_j= \underbrace{b(\varphi_i)}_{r_i}
$$

ist. Für das Gesamtsystem ergibt sich das lineare Gleichungssystem

$$
\mathbf{K} \mathbf{\hat{w}} = \boldsymbol{r}.
$${#eq-lin-gleichungssystem}

mit
$$
\begin{align}
&\mathbf{K} &&= k_{ij} &&= a(\varphi_j, \varphi_i) \\
&\boldsymbol{r} &&= r_i    &&= b(\varphi_i) \quad \text{mit} \quad i,j = 1,...,N,
\end{align}
$$

$\mathbf{K}$ bezeichnet die Gesamtsteifigkeitsmatrix, $\boldsymbol{r}$ den Lastvektor und $\boldsymbol{\hat{w}}$ den unbekannten, zu approixmierenden Verschiebungsvektor. Die Bilinearform (@eq-bilinearform) wird für jedes einzelne Element ausgewertet, wodurch sich die jeweiligen Elementsteifigkeitsmatrizen ergeben. Durch die Assemblierung der Elementsteifigkeitsmatrizen lässt sich die globale Steifigkeitmatrix ableiten. Die gleiche Vorgehensweise wird bei der Assemblierung des globalen Lastvektors verwendet. Die entsprechenden Bezeichnungen für ein Element sind $\mathbf{k^e_{ij}}$ für die Elementsteifigkeitsmatrix, $\boldsymbol{r^e}$ für den Elementlastvektor und $\boldsymbol{\hat{w}^e}$ für den Knotenverschiebungsvektor (siehe @tbl-Variablen).


|                     | Gesamtsystem         | Element|
|:--------------------|:--------------------:|:-----------:|
| Bilinearform (Variationsproblem) | $a(w, \delta w)$ | $a(w^e, \delta w^e)$ | 
| Steifigkeitsmatrix  | $\mathbf{K}$         |$\mathbf{k_{ij}^e}$|
| Bilinearform (Steifigkeitsmatrix) | $a(\varphi_j, \varphi_i)$ | $a(\varphi^e_j, \varphi^e_i)$|
| Lastvektor          | $\mathbf{r}$         |$\mathbf{r^e}$|
| Verschiebungsvektor | $\mathbf{\hat{w}}$   |$\mathbf{\hat{w}^e}$|

: Variablen des linearen Gleichungssystem für das Gesamtsystem und elementweise. {#tbl-Variablen}













<!-- 
### Parametrisierung (Jacobi-Matrix)

Analog zu Kapitel ... erfolgt die Abbildung der physikalischen Koordinaten $(x,y) \in [(x_1,y_1),(x_2,y_2),(x_3,y_3),(x_4,y_4)]$, auf die Referenzkoordinaten $(\xi,\eta) \text{ mit} -1 \le \xi,\eta \le 1$, durch Bestimmung der Bilinearform $\hat{a}$ und  der Linearform $\hat{b}$. Für die Platte ergibt sich somit aus dem Variationsproblem (@eq-variationsproblem) die Gleichung 
$$
\hat{a}(\hat{w}, \hat{\delta w}) = \hat{b}(\hat{\delta w})
$${#eq-diffgl-referenzkoordinaten}

Es ergeben sich die Bilinearform 
$$ 
\begin{align}
&\hat{a}(\hat{w}, \hat{\delta w})  
= D \int_{\Omega}
&&\hat{w}_{,xx}(\underline{F}^{-1}(x,y)) \cdot \hat{\delta w}_{,xx}(\underline{F}^{-1}(x,y)) \\
&\qquad &&+ 2 \hat{w}_{,xy}(\underline{F}^{-1}(x,y)) \cdot \hat{\delta w}_{,xy}(\underline{F}^{-1}(x,y)) \\
\\
&\qquad &&+ \hat{w}_{,yy}(\underline{F}^{-1}(x,y)) \cdot \hat{\delta w}_{,yy}(\underline{F}^{-1}(x,y)) 
\quad d \Omega \\
\end{align} 
$$ {#eq-ahat}

und die Linearform 
$$ 
\begin{align}
&\hat{b}(\hat{\delta w})  
= \int_{\Omega} q \cdot \delta w(\underline{F}^{-1}(x,y)) \quad d \Omega
\end{align} 
$$ {#eq-bhat}

Für die Parametrisierung werden die Variablen $\beta^x$ und $\beta^y$ als Rotation der Normalen, bezogen auf die unverformte Plattenebene, innerhalb der $x-z$-Ebene bzw. der $y-z$-Ebene mit 
$$
\beta^x(x,y) = \theta_y (x,y) = - \frac{\partial w(x,y)}{\partial x}
\qquad  \text{und} \qquad 
\beta^y(x,y) = \theta_x (x,y) = - \frac{\partial w(x,y)}{\partial y}
$$

eingeführt. Mittels der Substitution von 
$$
\underline{F}^{-1}(x,y) = 
\begin{cases} 
F_x^{-1}(x,y)\quad & \to \quad \xi(x,y) \\
F_y^{-1}(x,y)\quad & \to \quad \eta(x,y)
\end{cases}
$$

und der Darstellung der Bilinearform als Matrix-Vektor Produkt resultiert
$$
\hat{a}(\hat{w}, \hat{\delta w})  
= D \int_{-1}^1 \int_{-1}^1 [\beta]^T [\delta \beta] \quad d\xi d\eta
$$

mit den Vektoren 
$$
\underline{\beta} = 
\left[ \begin{array}{center} 
\beta^x_{,x} \\
\beta^y_{,y}\\
\beta^x_{,y}+\beta^y_{,x}
\end{array}\right] 
\qquad \qquad \text{und} \qquad \qquad
\underline{\delta\beta} = 
\left[ \begin{array}{center} 
\delta\beta^x_{,x} \\
\delta\beta^y_{,y}\\
\delta\beta^x_{,y}+\delta\beta^y_{,x}
\end{array}\right] .
$$


Entsprechend der Herleitung der Transformationsmatrix in Kapitel ... ergeben sich die Vektoren zu 

$$ 
\begin{align}
\underline{\beta} &= 
\left[ \begin{array}{center} 
j_{11} \frac{\partial \beta^x(\xi(x,y),\eta(x,y))}{\partial x} +
j_{12} \frac{\partial \beta^x(\xi(x,y),\eta(x,y))}{\partial y} \\
j_{21} \frac{\partial \beta^y(\xi(x,y),\eta(x,y))}{\partial x} +
j_{22} \frac{\partial \beta^y(\xi(x,y),\eta(x,y))}{\partial y} \\
j_{11} \frac{\partial \beta^y(\xi(x,y),\eta(x,y))}{\partial x} + 
j_{12} \frac{\partial \beta^y(\xi(x,y),\eta(x,y))}{\partial y} + 
j_{21} \frac{\partial \beta^x(\xi(x,y),\eta(x,y))}{\partial x} +
j_{22} \frac{\partial \beta^x(\xi(x,y),\eta(x,y))}{\partial y}
\end{array}\right] \\
\underline{\delta\beta} &= 
\left[ \begin{array}{center} 
j_{11} \frac{\partial \delta\beta^x(\xi(x,y),\eta(x,y))}{\partial x} +
j_{12} \frac{\partial \delta\beta^x(\xi(x,y),\eta(x,y))}{\partial y} \\
j_{21} \frac{\partial \delta\beta^y(\xi(x,y),\eta(x,y))}{\partial x} +
j_{22} \frac{\partial \delta\beta^y(\xi(x,y),\eta(x,y))}{\partial y} \\
j_{11} \frac{\partial \delta\beta^y(\xi(x,y),\eta(x,y))}{\partial x} + 
j_{12} \frac{\partial \delta\beta^y(\xi(x,y),\eta(x,y))}{\partial y} + 
j_{21} \frac{\partial \delta\beta^x(\xi(x,y),\eta(x,y))}{\partial x} +
j_{22} \frac{\partial \delta\beta^x(\xi(x,y),\eta(x,y))}{\partial y}
\end{array}\right] 
\end{align}
$$ {#eq-Beta}

mit den Komponenten der inversen Transformationsmatrix definiert
$$
\begin{align}
j_{11} &= \frac{\partial F_x^{-1}(x,y)}{\partial x} \qquad
j_{12} &= \frac{\partial F_y^{-1}(x,y)}{\partial x} \\
j_{21} &= \frac{\partial F_x^{-1}(x,y)}{\partial y} \qquad
j_{22} &= \frac{\partial F_y^{-1}(x,y)}{\partial y} \\
\end{align}
$$

-----------------------------------------

$$
K u = r
$$

$$
u^e = 
\left[ \begin{array}{center} 
w_1 \\
\theta_{x1} \\
\theta_{y1} \\
w_2 \\
\theta_{x2} \\
\theta_{y2} \\
w_3 \\
\theta_{x3} \\
\theta_{y3} \\
w_4 \\
\theta_{x4} \\
\theta_{y4}
\end{array}\right] 
=
\left[ \begin{array}{center} 
w_1 \\
\frac{\partial w_1}{\partial y} \\
-\frac{\partial w_1}{\partial x} \\
w_2 \\
\frac{\partial w_2}{\partial y} \\
-\frac{\partial w_2}{\partial x} \\
w_3 \\
\frac{\partial w_3}{\partial y} \\
-\frac{\partial w_3}{\partial x} \\
w_4 \\
\frac{\partial w_4}{\partial y} \\
-\frac{\partial w_4}{\partial x}
\end{array}\right] 
$$


$$
\begin{align}
w_{,xx} &= \beta_{,x} &&= H^x_{,x} U_n \\
w_{,yy} &= \beta_{,y} &&= H^y_{,y} U_n \\
w_{,xy} &= \beta_{,x} + \beta_{,y} &&= (H^x_{,y} + H^y_{,x}) U_n \\
\end{align}
$$

$$ 
\begin{align}
K^e &= \int_{\Omega} [B]^T [D_b][B] d \Omega \\
&= 
\left[ \begin{array}{center} 
\frac{\partial H^x}{\partial x} \\
\frac{\partial H^y}{\partial y} \\
\frac{\partial H^x}{\partial y}+\frac{\partial H^y}{\partial x}
\end{array}\right]
\end{align}
$$ {#eq-bilinearform-ahat}

$$ 
a(w, \delta w) = \int_{\Omega} D 
\left[ \begin{array}{center} 
w_{,xx} &
w_{,yy} &
2w_{,xy}
\end{array}\right]
\begin{bmatrix} D & D\nu & 0 \\ D\nu & D & 0 \\ 0 & 0 & D\frac{1-\nu}{2} \end{bmatrix}
\left[ \begin{array}{center} 
\delta w_{,xx} \\
\delta w_{,yy} \\
2\delta w_{,xy}
\end{array}\right]
d \Omega 
$$


$$ 
\begin{align}
\hat{a}(\hat{w}, \hat{\delta w})  
&= \int_{\Omega}  D
\left[ \begin{array}{center} 
w_{,xx}(\underline{F}^{-1}(x,y)) &
w_{,yy}(\underline{F}^{-1}(x,y)) &
w_{,xy}(\underline{F}^{-1}(x,y))
\end{array}\right]
\left[ \begin{array}{center} 
\delta w_{,xx}(\underline{F}^{-1}(x,y)) \\
\delta w_{,yy}(\underline{F}^{-1}(x,y)) \\
2 \delta w_{,xy}(\underline{F}^{-1}(x,y))
\end{array}\right]
d \Omega \\
\end{align} 
$$ {#eq-black-scholes-04}


--------------------------------------------
Bilinearform $a:V \times V \to \mathbb{R}$
zur "Referenz"-Bilinearform $\hat{a}: \hat{V} \times \hat{V}  \to \mathbb{R}$

$$
\hat{a}(\hat{w}, \hat{\delta w}) = \hat{a}(\hat{w} \circ \underline{F}^{-1}(x,y), \hat{\delta w}\circ \underline{F}^{-1}(x,y))
$$

Linearform $b:V \to \mathbb{R}$
zur "Referenz"-Linearform $\hat{b}: \hat{V} \to \mathbb{R}$

$$
\hat{b}(\hat{\delta w}) = \hat{b}(\hat{\delta w}\circ \underline{F}^{-1}(x,y))
$$



$$
\mathbf{K^e} = \int_{\Omega} [B]^T [D_b][B]
$$




-----------------------------
Strong form: 
    Find a function which satisfies an equation at each point in the considered domain
Weak form:  
    Find a function, for which a scalar valued equation holds for any test function


Why the names strong form and weak form?
Strong form: 
    Requirements on u
    - fulfill the differential equation point wise (strongly) for each x ∈ [0, l] I two times differentiable
Weak form: 
    Requirements on u
    - differential equation fulfilled in an integral sense
    - one time differentiable (Fish and Belytschko 2007, p. 49)
 -->
